[2021-05-17 00:43:29,189] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.load_data 2021-05-16T19:43:08.652023+00:00 [queued]>
[2021-05-17 00:43:29,204] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.load_data 2021-05-16T19:43:08.652023+00:00 [queued]>
[2021-05-17 00:43:29,204] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 00:43:29,204] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-05-17 00:43:29,204] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 00:43:29,242] {taskinstance.py:900} INFO - Executing <Task(GoogleCloudStorageToBigQueryOperator): load_data> on 2021-05-16T19:43:08.652023+00:00
[2021-05-17 00:43:29,245] {standard_task_runner.py:53} INFO - Started process 29304 to run task
[2021-05-17 00:43:29,317] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: bigquery_data_load.load_data 2021-05-16T19:43:08.652023+00:00 [running]> alieymsxxn
[2021-05-17 00:43:36,525] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=bigquery_data_load, task_id=load_data, execution_date=20210516T194308, start_date=20210516T194329, end_date=20210516T194336
[2021-05-17 00:43:39,144] {logging_mixin.py:112} INFO - [2021-05-17 00:43:39,143] {local_task_job.py:103} INFO - Task exited with return code 0
