[2021-05-16 22:00:03,732] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.load_data 2021-05-16T16:00:00+00:00 [queued]>
[2021-05-16 22:00:03,739] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: bigquery_data_load.load_data 2021-05-16T16:00:00+00:00 [queued]>
[2021-05-16 22:00:03,739] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 22:00:03,739] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-05-16 22:00:03,739] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-05-16 22:00:03,776] {taskinstance.py:900} INFO - Executing <Task(GoogleCloudStorageToBigQueryOperator): load_data> on 2021-05-16T16:00:00+00:00
[2021-05-16 22:00:03,783] {standard_task_runner.py:53} INFO - Started process 20299 to run task
[2021-05-16 22:00:03,857] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: bigquery_data_load.load_data 2021-05-16T16:00:00+00:00 [running]> alieymsxxn
[2021-05-16 22:00:11,545] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=bigquery_data_load, task_id=load_data, execution_date=20210516T160000, start_date=20210516T170003, end_date=20210516T170011
[2021-05-16 22:00:13,688] {logging_mixin.py:112} INFO - [2021-05-16 22:00:13,687] {local_task_job.py:103} INFO - Task exited with return code 0
